insert into tb_category (name)
values ('Electronics'),
       ('Books'),
       ('Home & Kitchen'),
         ('Fashion'),
         ('Toys & Games'),
         ('Beauty'),
         ('Sports & Outdoors'),
         ('Automotive'),
         ('Grocery'),
         ('Health & Personal Care'),
            ('Baby'),
            ('Pet Supplies'),
            ('Tools & Home Improvement'),
            ('Office Products'),
            ('Software'),
            ('Video Games'),
            ('Arts, Crafts & Sewing'),
            ('Industrial & Scientific'),
            ('Musical Instruments'),
            ('Kindle Store'),
            ('Movies & TV'),
            ('CDs & Vinyl'),
            ('Cell Phones & Accessories'),
            ('Amazon Devices'),
            ('Appliances'),
            ('Apps & Games'),
            ('Gift Cards'),
            ('Collectibles & Fine Art'),
            ('Digital Music'),
            ('Magazine Subscriptions'),
            ('Prime Pantry'),
            ('Specialty Stores'),
            ('Amazon Fresh'),
            ('Amazon Warehouse'),
            ('Automotive Parts & Accessories'),
            ('Baby Products'),
            ('Beauty & Personal Care'),
            ('Books & Audible'),
            ('Clothing, Shoes & Jewelry'),
            ('Electronics & Computers'),
            ('Grocery & Gourmet Food'),
            ('Health, Household & Baby Care'),
            ('Home, Garden & Tools'),
            ('Movies, Music & Games'),
            ('Sports & Outdoors'),
            ('Toys, Kids & Baby');